spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/afterglow}
spring.datasource.username=${DATABASE_USERNAME:afterglow}
spring.datasource.password=${DATABASE_PASSWORD:afterglow}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
